services:
  - type: web
    name: ml-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
